### ISSUE TITLE
Can we have a 0.12.1 in the meantime that can properly compile again?

### ISSUE THREAD

**Issue by slyshykO** [emberian/evdev#107] opened 2022-11-07 16:58 UTC
https://github.com/emberian/evdev/pull/98#issuecomment-1275314642

**Comment by LinusCDE** [comment] 2022-11-18 17:11
I second a 0.12.1 release of the current state. At [libremarkable](https://github.com/canselcik/libremarkable/), we encountered a new issue, where some older bitvec version is causin issues now.

I couldn't update to 0.12.0 due to https://github.com/canselcik/libremarkable/pull/107, which got fixed in https://github.com/emberian/evdev/pull/96, but has no official release yet.

Now, we have the dilemma: Updating to 0.12.0, fixes bitvec (because recent enough) but breaks evdev for us (cross compiling for armv7 which is the target hw). And the current version we're using (`<=0.11.3`) now has the issue caused by the older bitvec version.

Since we publish releases to crates.io, we can't use git-links for dependencies, so we cannot really fix it rn. Some cargo replace option might be able to patch it, but have not found a way to patch or replace the dependency of a dependency yet.

So: Please just release a 0.12.1 :smiley:

**Comment by ToxicMushroom** [comment] 2022-12-08 01:08
any news on this ?

**Comment by jeff-hiner** [comment] 2022-12-08 06:04
@emberian I think is the only one who can cut a release, or maybe @coolreader18 ?

**Comment by coolreader18** [comment] 2022-12-08 23:25
Oh, yep, I can do that. Sorry, I've sorta declared bankruptcy on my github notifications so I didn't see this; should probably clean them up to make em usable again.

**Comment by coolreader18** [comment] 2022-12-09 18:49
Alright, 0.12.1 is released!

**Closed** 2022-12-09 18:53 UTC
