### ISSUE TITLE
evdev uses 100% of CPU

### ISSUE THREAD

**Issue by vlisivka** [emberian/evdev#11] opened 2018-07-24 14:13 UTC
Evdev uses 100% of CPU because device open with O_NONBLOCK flag, so call to read returns early.

**Comment by vlisivka** [comment] 2018-07-24 14:13
Pull request:
https://github.com/cmr/evdev/pull/10

**Comment by plafue** [comment] 2019-01-07 13:06
@cmr I'm seeing the same behaviour as reported by @vlisivka ... Any chance their changes could be merged to evdev?

**Comment by vlisivka** [comment] 2019-01-07 14:48
@plafue I updated pull request: https://github.com/cmr/evdev/pull/13 .
As temporary workaround, you can use my fork.

`evdev = { git = "https://github.com/vlisivka/evdev", rev = "10097307" }`

**Comment by plafue** [comment] 2019-01-07 15:20
Thanks for the heads up, @vlisivka! I created a fork of your repo myself and I've been using it for a while. It'd be great to have the changes merged upstream, though

**Comment by emberian** [comment] 2020-05-04 05:43
@vlisivka @plafue yeah, the read returns early, but it returns with EAGAIN, breaking out of the loop. the intended usecase of this crate was to epoll on the device fd and only check for events when ready. the evtest example doesn't do this though, which was quite lazy for me.

**Comment by emberian** [comment] 2020-05-04 05:47
Closing as not a bug, but the next version of this crate will address this shortcoming by exposing a synchronous API for those usecases.

**Closed** 2020-05-04 05:47 UTC
